### ISSUE TITLE
Include statement incorrect

### ISSUE THREAD

**Issue by codyvilliam** [sparkfun/SparkFun_MPL3115A2_Particle_Library#1]
In the SparkFun_MPL3115A2.cpp file it says #include "SparkFunMPL3115A2.h" when I believe it should be #include "SparkFun_MPL3115A2.h". I am receiving errors because it says "SparkFunMPL3115A2.h" does not exist.

**Comment by JoelEB** [comment]
You are correct. I thought I fixed all of the includes when I changed to the underscore in the name but missed this one. It should be fixed now. Thanks!
